package webServ;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ConnectServiceSoap", targetNamespace = "http://tempuri.org/")
public interface ConnectServiceSoap {

	/**
	 * 
	 * @param username
	 * @param password
	 * @return returns boolean
	 */
	@WebMethod(operationName = "Authenticate247Connect", action = "http://tempuri.org/Authenticate247Connect")
	@WebResult(name = "Authenticate247ConnectResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Authenticate247Connect", targetNamespace = "http://tempuri.org/", className = "webServ.Authenticate247Connect")
	@ResponseWrapper(localName = "Authenticate247ConnectResponse", targetNamespace = "http://tempuri.org/", className = "webServ.Authenticate247ConnectResponse")
	public boolean authenticate247Connect(
			@WebParam(name = "username", targetNamespace = "http://tempuri.org/") String username,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password);

}
