package webServ;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ConnectService service = new ConnectService();
 * ConnectServiceSoap portType = service.getConnectServiceSoap();
 * portType.authenticate247Connect(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ConnectService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://connect.247customer.com/connect247service/connect247.asmx?wsdl")
public class ConnectService extends Service {

	private final static URL CONNECTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(webServ.ConnectService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = webServ.ConnectService.class.getResource(".");
			url = new URL(baseUrl,
					"http://connect.247customer.com/connect247service/connect247.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://connect.247customer.com/connect247service/connect247.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CONNECTSERVICE_WSDL_LOCATION = url;
	}

	public ConnectService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ConnectService() {
		super(CONNECTSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"ConnectService"));
	}

	/**
	 * 
	 * @return returns ConnectServiceSoap
	 */
	@WebEndpoint(name = "ConnectServiceSoap")
	public ConnectServiceSoap getConnectServiceSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"ConnectServiceSoap"), ConnectServiceSoap.class);
	}

	/**
	 * 
	 * @return returns ConnectServiceSoap
	 */
	@WebEndpoint(name = "ConnectServiceSoap12")
	public ConnectServiceSoap getConnectServiceSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"ConnectServiceSoap12"), ConnectServiceSoap.class);
	}

}
