package peopleInTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "formulaHRServicesSoap", targetNamespace = "http://tempuri.org/")
public interface FormulaHRServicesSoap {

	/**
	 * 
	 * @param fromDate
	 * @param toDate
	 * @param password
	 * @return returns peopleIn.ArrayOfEmpNewJoinee
	 */
	@WebMethod(operationName = "GetNewJoineeDetails", action = "http://tempuri.org/GetNewJoineeDetails")
	@WebResult(name = "GetNewJoineeDetailsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetNewJoineeDetails", targetNamespace = "http://tempuri.org/", className = "peopleIn.GetNewJoineeDetails")
	@ResponseWrapper(localName = "GetNewJoineeDetailsResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.GetNewJoineeDetailsResponse")
	public ArrayOfEmpNewJoinee getNewJoineeDetails(
			@WebParam(name = "Password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "FromDate", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar fromDate,
			@WebParam(name = "ToDate", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar toDate);

	/**
	 * 
	 * @return returns peopleIn.ArrayOfOrgMasProgram
	 */
	@WebMethod(operationName = "OrgMasProgramList", action = "http://tempuri.org/OrgMasProgramList")
	@WebResult(name = "OrgMasProgramListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "OrgMasProgramList", targetNamespace = "http://tempuri.org/", className = "peopleIn.OrgMasProgramList")
	@ResponseWrapper(localName = "OrgMasProgramListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.OrgMasProgramListResponse")
	public ArrayOfOrgMasProgram orgMasProgramList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfOrgMasSubProgram
	 */
	@WebMethod(operationName = "OrgMasSubProgramList", action = "http://tempuri.org/OrgMasSubProgramList")
	@WebResult(name = "OrgMasSubProgramListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "OrgMasSubProgramList", targetNamespace = "http://tempuri.org/", className = "peopleIn.OrgMasSubProgramList")
	@ResponseWrapper(localName = "OrgMasSubProgramListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.OrgMasSubProgramListResponse")
	public ArrayOfOrgMasSubProgram orgMasSubProgramList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasNationality
	 */
	@WebMethod(operationName = "EmpMasNationalityList", action = "http://tempuri.org/EmpMasNationalityList")
	@WebResult(name = "EmpMasNationalityListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasNationalityList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasNationalityList")
	@ResponseWrapper(localName = "EmpMasNationalityListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasNationalityListResponse")
	public ArrayOfEmpMasNationality empMasNationalityList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasReligion
	 */
	@WebMethod(operationName = "EmpMasReligionList", action = "http://tempuri.org/EmpMasReligionList")
	@WebResult(name = "EmpMasReligionListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasReligionList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasReligionList")
	@ResponseWrapper(localName = "EmpMasReligionListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasReligionListResponse")
	public ArrayOfEmpMasReligion empMasReligionList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasLanguage
	 */
	@WebMethod(operationName = "EmpMasLanguageList", action = "http://tempuri.org/EmpMasLanguageList")
	@WebResult(name = "EmpMasLanguageListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasLanguageList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasLanguageList")
	@ResponseWrapper(localName = "EmpMasLanguageListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasLanguageListResponse")
	public ArrayOfEmpMasLanguage empMasLanguageList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasBloodGroup
	 */
	@WebMethod(operationName = "EmpMasBloodGroupList", action = "http://tempuri.org/EmpMasBloodGroupList")
	@WebResult(name = "EmpMasBloodGroupListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasBloodGroupList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasBloodGroupList")
	@ResponseWrapper(localName = "EmpMasBloodGroupListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasBloodGroupListResponse")
	public ArrayOfEmpMasBloodGroup empMasBloodGroupList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasAccommodationType
	 */
	@WebMethod(operationName = "EmpMasAccommodationTypeList", action = "http://tempuri.org/EmpMasAccommodationTypeList")
	@WebResult(name = "EmpMasAccommodationTypeListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasAccommodationTypeList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasAccommodationTypeList")
	@ResponseWrapper(localName = "EmpMasAccommodationTypeListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasAccommodationTypeListResponse")
	public ArrayOfEmpMasAccommodationType empMasAccommodationTypeList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasState
	 */
	@WebMethod(operationName = "EmpMasStateList", action = "http://tempuri.org/EmpMasStateList")
	@WebResult(name = "EmpMasStateListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasStateList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasStateList")
	@ResponseWrapper(localName = "EmpMasStateListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasStateListResponse")
	public ArrayOfEmpMasState empMasStateList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasCity
	 */
	@WebMethod(operationName = "EmpMasCityList", action = "http://tempuri.org/EmpMasCityList")
	@WebResult(name = "EmpMasCityListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasCityList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCityList")
	@ResponseWrapper(localName = "EmpMasCityListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCityListResponse")
	public ArrayOfEmpMasCity empMasCityList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasCountry
	 */
	@WebMethod(operationName = "EmpMasCountryList", action = "http://tempuri.org/EmpMasCountryList")
	@WebResult(name = "EmpMasCountryListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasCountryList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCountryList")
	@ResponseWrapper(localName = "EmpMasCountryListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCountryListResponse")
	public ArrayOfEmpMasCountry empMasCountryList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasRelationship
	 */
	@WebMethod(operationName = "EmpMasRelationshipList", action = "http://tempuri.org/EmpMasRelationshipList")
	@WebResult(name = "EmpMasRelationshipListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasRelationshipList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasRelationshipList")
	@ResponseWrapper(localName = "EmpMasRelationshipListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasRelationshipListResponse")
	public ArrayOfEmpMasRelationship empMasRelationshipList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasCaste
	 */
	@WebMethod(operationName = "EmpMasCasteList", action = "http://tempuri.org/EmpMasCasteList")
	@WebResult(name = "EmpMasCasteListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasCasteList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCasteList")
	@ResponseWrapper(localName = "EmpMasCasteListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCasteListResponse")
	public ArrayOfEmpMasCaste empMasCasteList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasQualificationGroup
	 */
	@WebMethod(operationName = "EmpMasQualificationGroupList", action = "http://tempuri.org/EmpMasQualificationGroupList")
	@WebResult(name = "EmpMasQualificationGroupListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasQualificationGroupList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasQualificationGroupList")
	@ResponseWrapper(localName = "EmpMasQualificationGroupListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasQualificationGroupListResponse")
	public ArrayOfEmpMasQualificationGroup empMasQualificationGroupList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasQualification
	 */
	@WebMethod(operationName = "EmpMasQualificationList", action = "http://tempuri.org/EmpMasQualificationList")
	@WebResult(name = "EmpMasQualificationListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasQualificationList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasQualificationList")
	@ResponseWrapper(localName = "EmpMasQualificationListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasQualificationListResponse")
	public ArrayOfEmpMasQualification empMasQualificationList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasSpecialisation
	 */
	@WebMethod(operationName = "EmpMasSpecialisationList", action = "http://tempuri.org/EmpMasSpecialisationList")
	@WebResult(name = "EmpMasSpecialisationListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasSpecialisationList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasSpecialisationList")
	@ResponseWrapper(localName = "EmpMasSpecialisationListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasSpecialisationListResponse")
	public ArrayOfEmpMasSpecialisation empMasSpecialisationList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasAchievement
	 */
	@WebMethod(operationName = "EmpMasAchievementList", action = "http://tempuri.org/EmpMasAchievementList")
	@WebResult(name = "EmpMasAchievementListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasAchievementList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasAchievementList")
	@ResponseWrapper(localName = "EmpMasAchievementListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasAchievementListResponse")
	public ArrayOfEmpMasAchievement empMasAchievementList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasCourseAppraisal
	 */
	@WebMethod(operationName = "EmpMasCourseAppraisalList", action = "http://tempuri.org/EmpMasCourseAppraisalList")
	@WebResult(name = "EmpMasCourseAppraisalListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasCourseAppraisalList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCourseAppraisalList")
	@ResponseWrapper(localName = "EmpMasCourseAppraisalListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCourseAppraisalListResponse")
	public ArrayOfEmpMasCourseAppraisal empMasCourseAppraisalList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasCourseCategory
	 */
	@WebMethod(operationName = "EmpMasCourseCategoryList", action = "http://tempuri.org/EmpMasCourseCategoryList")
	@WebResult(name = "EmpMasCourseCategoryListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasCourseCategoryList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCourseCategoryList")
	@ResponseWrapper(localName = "EmpMasCourseCategoryListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCourseCategoryListResponse")
	public ArrayOfEmpMasCourseCategory empMasCourseCategoryList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasCourseType
	 */
	@WebMethod(operationName = "EmpMasCourseTypeList", action = "http://tempuri.org/EmpMasCourseTypeList")
	@WebResult(name = "EmpMasCourseTypeListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasCourseTypeList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCourseTypeList")
	@ResponseWrapper(localName = "EmpMasCourseTypeListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasCourseTypeListResponse")
	public ArrayOfEmpMasCourseType empMasCourseTypeList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasZone
	 */
	@WebMethod(operationName = "EmpMasZoneList", action = "http://tempuri.org/EmpMasZoneList")
	@WebResult(name = "EmpMasZoneListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasZoneList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasZoneList")
	@ResponseWrapper(localName = "EmpMasZoneListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasZoneListResponse")
	public ArrayOfEmpMasZone empMasZoneList();

	/**
	 * 
	 * @return returns peopleIn.ArrayOfEmpMasArea
	 */
	@WebMethod(operationName = "EmpMasAreaList", action = "http://tempuri.org/EmpMasAreaList")
	@WebResult(name = "EmpMasAreaListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EmpMasAreaList", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasAreaList")
	@ResponseWrapper(localName = "EmpMasAreaListResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.EmpMasAreaListResponse")
	public ArrayOfEmpMasArea empMasAreaList();

	/**
	 * 
	 * @param middleName
	 * @param lastName
	 * @param photograph
	 * @param dateofBirth
	 * @param cityCode
	 * @param stateCode
	 * @param programCode
	 * @param residencePhone
	 * @param cityOthers
	 * @param candidateID
	 * @param pincode
	 * @param relevantExperience
	 * @param qualificationGroupCode
	 * @param title
	 * @param subProgramCode
	 * @param source
	 * @param mobilePhone
	 * @param fatherHusbandName
	 * @param currentAddress
	 * @param recruitmentSummary
	 * @param gender
	 * @param firstName
	 * @param fatherHusband
	 * @param nonRelevantExperience
	 * @return returns boolean
	 */
	@WebMethod(operationName = "CandidateSave", action = "http://tempuri.org/CandidateSave")
	@WebResult(name = "CandidateSaveResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CandidateSave", targetNamespace = "http://tempuri.org/", className = "peopleIn.CandidateSave")
	@ResponseWrapper(localName = "CandidateSaveResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.CandidateSaveResponse")
	public boolean candidateSave(
			@WebParam(name = "Title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "FirstName", targetNamespace = "http://tempuri.org/") String firstName,
			@WebParam(name = "MiddleName", targetNamespace = "http://tempuri.org/") String middleName,
			@WebParam(name = "LastName", targetNamespace = "http://tempuri.org/") String lastName,
			@WebParam(name = "Gender", targetNamespace = "http://tempuri.org/") String gender,
			@WebParam(name = "FatherHusband", targetNamespace = "http://tempuri.org/") String fatherHusband,
			@WebParam(name = "FatherHusbandName", targetNamespace = "http://tempuri.org/") String fatherHusbandName,
			@WebParam(name = "DateofBirth", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar dateofBirth,
			@WebParam(name = "CurrentAddress", targetNamespace = "http://tempuri.org/") String currentAddress,
			@WebParam(name = "CityCode", targetNamespace = "http://tempuri.org/") int cityCode,
			@WebParam(name = "CityOthers", targetNamespace = "http://tempuri.org/") String cityOthers,
			@WebParam(name = "StateCode", targetNamespace = "http://tempuri.org/") int stateCode,
			@WebParam(name = "Pincode", targetNamespace = "http://tempuri.org/") int pincode,
			@WebParam(name = "ResidencePhone", targetNamespace = "http://tempuri.org/") String residencePhone,
			@WebParam(name = "MobilePhone", targetNamespace = "http://tempuri.org/") String mobilePhone,
			@WebParam(name = "Source", targetNamespace = "http://tempuri.org/") String source,
			@WebParam(name = "ProgramCode", targetNamespace = "http://tempuri.org/") int programCode,
			@WebParam(name = "SubProgramCode", targetNamespace = "http://tempuri.org/") int subProgramCode,
			@WebParam(name = "CandidateID", targetNamespace = "http://tempuri.org/") String candidateID,
			@WebParam(name = "QualificationGroupCode", targetNamespace = "http://tempuri.org/") int qualificationGroupCode,
			@WebParam(name = "RelevantExperience", targetNamespace = "http://tempuri.org/") double relevantExperience,
			@WebParam(name = "NonRelevantExperience", targetNamespace = "http://tempuri.org/") double nonRelevantExperience,
			@WebParam(name = "RecruitmentSummary", targetNamespace = "http://tempuri.org/") byte[] recruitmentSummary,
			@WebParam(name = "Photograph", targetNamespace = "http://tempuri.org/") byte[] photograph);

	/**
	 * 
	 * @param middleName
	 * @param lastName
	 * @param photograph
	 * @param dateofBirth
	 * @param cityCode
	 * @param stateCode
	 * @param programCode
	 * @param residencePhone
	 * @param cityOthers
	 * @param candidateID
	 * @param pincode
	 * @param relevantExperience
	 * @param qualificationGroupCode
	 * @param title
	 * @param subProgramCode
	 * @param source
	 * @param mobilePhone
	 * @param fatherHusbandName
	 * @param currentAddress
	 * @param recruitmentSummary
	 * @param gender
	 * @param firstName
	 * @param fatherHusband
	 * @param nonRelevantExperience
	 * @return returns boolean
	 */
	@WebMethod(operationName = "CandidateSaveIMG", action = "http://tempuri.org/CandidateSaveIMG")
	@WebResult(name = "CandidateSaveIMGResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CandidateSaveIMG", targetNamespace = "http://tempuri.org/", className = "peopleIn.CandidateSaveIMG")
	@ResponseWrapper(localName = "CandidateSaveIMGResponse", targetNamespace = "http://tempuri.org/", className = "peopleIn.CandidateSaveIMGResponse")
	public boolean candidateSaveIMG(
			@WebParam(name = "Title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "FirstName", targetNamespace = "http://tempuri.org/") String firstName,
			@WebParam(name = "MiddleName", targetNamespace = "http://tempuri.org/") String middleName,
			@WebParam(name = "LastName", targetNamespace = "http://tempuri.org/") String lastName,
			@WebParam(name = "Gender", targetNamespace = "http://tempuri.org/") String gender,
			@WebParam(name = "FatherHusband", targetNamespace = "http://tempuri.org/") String fatherHusband,
			@WebParam(name = "FatherHusbandName", targetNamespace = "http://tempuri.org/") String fatherHusbandName,
			@WebParam(name = "DateofBirth", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar dateofBirth,
			@WebParam(name = "CurrentAddress", targetNamespace = "http://tempuri.org/") String currentAddress,
			@WebParam(name = "CityCode", targetNamespace = "http://tempuri.org/") int cityCode,
			@WebParam(name = "CityOthers", targetNamespace = "http://tempuri.org/") String cityOthers,
			@WebParam(name = "StateCode", targetNamespace = "http://tempuri.org/") int stateCode,
			@WebParam(name = "Pincode", targetNamespace = "http://tempuri.org/") int pincode,
			@WebParam(name = "ResidencePhone", targetNamespace = "http://tempuri.org/") String residencePhone,
			@WebParam(name = "MobilePhone", targetNamespace = "http://tempuri.org/") String mobilePhone,
			@WebParam(name = "Source", targetNamespace = "http://tempuri.org/") String source,
			@WebParam(name = "ProgramCode", targetNamespace = "http://tempuri.org/") int programCode,
			@WebParam(name = "SubProgramCode", targetNamespace = "http://tempuri.org/") int subProgramCode,
			@WebParam(name = "CandidateID", targetNamespace = "http://tempuri.org/") String candidateID,
			@WebParam(name = "QualificationGroupCode", targetNamespace = "http://tempuri.org/") int qualificationGroupCode,
			@WebParam(name = "RelevantExperience", targetNamespace = "http://tempuri.org/") double relevantExperience,
			@WebParam(name = "NonRelevantExperience", targetNamespace = "http://tempuri.org/") double nonRelevantExperience,
			@WebParam(name = "RecruitmentSummary", targetNamespace = "http://tempuri.org/") byte[] recruitmentSummary,
			@WebParam(name = "Photograph", targetNamespace = "http://tempuri.org/") byte[] photograph);

}
