package peopleInLive;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * formulaHRServices service = new formulaHRServices();
 * FormulaHRServicesSoap portType = service.getFormulaHRServicesSoap();
 * portType.getNewJoineeDetails(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "formulaHRServices", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://247people.in/Services/formulaHRServices.asmx?wsdl")
public class FormulaHRServices extends Service {

	private final static URL FORMULAHRSERVICES_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(peopleInLive.FormulaHRServices.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = peopleInLive.FormulaHRServices.class.getResource(".");
			url = new URL(baseUrl,
					"http://247people.in/Services/formulaHRServices.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://247people.in/Services/formulaHRServices.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FORMULAHRSERVICES_WSDL_LOCATION = url;
	}

	public FormulaHRServices(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FormulaHRServices() {
		super(FORMULAHRSERVICES_WSDL_LOCATION, new QName("http://tempuri.org/",
				"formulaHRServices"));
	}

	/**
	 * 
	 * @return returns FormulaHRServicesSoap
	 */
	@WebEndpoint(name = "formulaHRServicesSoap")
	public FormulaHRServicesSoap getFormulaHRServicesSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"formulaHRServicesSoap"), FormulaHRServicesSoap.class);
	}

	/**
	 * 
	 * @return returns FormulaHRServicesSoap
	 */
	@WebEndpoint(name = "formulaHRServicesSoap12")
	public FormulaHRServicesSoap getFormulaHRServicesSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"formulaHRServicesSoap12"), FormulaHRServicesSoap.class);
	}

}
